### ISSUE TITLE
Request to join workgroup

### ISSUE THREAD

**Issue by drusso-rh** [ossf/wg-best-practices-os-developers#10]
Hello,

My name is Dave Russo and I work for Red Hat on the Product Security team (CRob's partner in crime). We are responsible for vulnerability response, governance and secure development and SDLC-like activities, and I would be interested in joining this workgroup to help contribute to the efforts for open source secure development practices.

Thanks!
Dave Russo

**Comment by xcorail** [comment]
Hey Dave 👋🏾 
Please send me your email address so that I can add you to the meetings

Cheers

**Comment by xcorail** [comment]
Invite send
