### ISSUE TITLE
VOTE - Adopt WG Charter

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/wg-best-practices-os-developers#103]
Team - please review our project charter:

 https://github.com/ossf/wg-best-practices-os-developers/blob/main/CHARTER.md

and provide any feedback.

Then please express your vote to adopt it or not by EoD 7Dec2022.

**Comment by drusso-rh** [comment]
I opened a PR to remove two references that don't exist. Aside from that I +1 the charter.

**Comment by ran-dall** [comment]
+1 ✅ Approve

**Comment by blabla1337** [comment]
+1

**Comment by balteravishay** [comment]
+1

**Comment by mrybczyn** [comment]
+1 approved

**Comment by torgo** [comment]
+1 for approval

**Comment by SecurityCRob** [comment]
The WG votes to adopt the charter on 7dec2022
