### ISSUE TITLE
Improve readme formatting

### ISSUE THREAD

**Issue by AdamKorcz** [ossf/wg-best-practices-os-developers#107]
I am seeing the Readme like this:

![best-practices-readme](https://user-images.githubusercontent.com/44787359/207376334-d31514e3-f273-47c6-86ee-10308c8d7f4d.png)

**Comment by SecurityCRob** [comment]
i adjusted the alignment of the image.  Does this display correctly now?

**Comment by AdamKorcz** [comment]
Yep!

**Comment by AdamKorcz** [comment]
Fixed in https://github.com/ossf/wg-best-practices-os-developers/commit/e42f9d665f953ef143174e7c5685faecaa53be84
