### ISSUE TITLE
Create a Vulnerabilities in Vendored Dependencies Guide

### ISSUE THREAD

**Issue by JLLeitschuh** [ossf/wg-best-practices-os-developers#114]
## Proposal

It's considered best-practice, when updating a dependency that fixes a vulnerability in a piece of software that vendors dependencies, ie. that can't be directly updated by the end-user, that the project issue their own disclosure of that vulnerability, and reach out to the CNA for the original vulnerability to add their advisory to the list of links.

This is the CVE way of communicating "we were impacted by this CVE, but we also fixed it".

## Notes

Vendoring doesn't always require that deps are committed to source code. Case in point: Gradle/Gradle

**Comment by JLLeitschuh** [comment]
Proposal:
https://docs.google.com/document/d/16JprHUpGO9f2hwQRjDJmAJrlCsJ38GQ5l3Rwd2qrr4s/edit

**Comment by SecurityCRob** [comment]
discussed in 14march wg call.  group agreed we should file a Pr to update the guide, comment there, and eventually merge the approved language
