### ISSUE TITLE
VOTE: Create Memory Safety SIG under BEST Practices WG

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/wg-best-practices-os-developers#126]
Team - During our 14March WG call(1) a proposal was made to create a new SIG under the BEST Practices working group that seeks to refine the OpenSSF's Mobilization plan stream 4(2) .  **To that end, we ask all eligible members(3) to express their opinion, ask questions, provide feedback, and ultimately vote for or against (or abstain) to adopt this work under our umbrella.**  

The core group has met several times(4) already and has a diverse group of folks participating so far and would benefit from our engagement and participation.  Their proposal can be found here(5).  Eligible WG members, please review these materials and express your opinion in this issue (as "+1", "-1", "Yes", "No", "Agree", "Disagree", "Abstain" or however you feel comfortable) **no later than 28March2023** so we can discuss any outstanding questions and determine next steps.  Thank you for your time and participation.

(1) - https://docs.google.com/document/d/1x-fMIt6ZIV6SM-M29xEVKeB505GbDzSIVXg-8uF_FQU/edit#heading=h.ol1uqtnxytpe 
(2) - https://8112310.fs1.hubspotusercontent-na1.net/hubfs/8112310/OpenSSF/White%20House%20OSS%20Mobilization%20Plan.pdf?hsCtaTracking=3b79d59d-e8d3-4c69-a67b-6b87b325313c%7C7a1a8b01-65ae-4bac-b97c-071dac09a2d8 
(3) - https://github.com/ossf/wg-best-practices-os-developers/blob/main/README.md#governance
(4) - https://docs.google.com/document/d/1Ehpp1UmAIqMs0ZdKr15sd5MS48OeaGKB9H40htVehs4/edit?usp=sharing
(5) - https://openssf.slack.com/files/U03451TRVHT/F04U8CVU85P/memory_safety_sig_proposal.pdf?origin_team=T019QHUBYQ3&origin_channel=C01AHCRP8BT

**Comment by ran-dall** [comment]
`+1`

**Comment by david-a-wheeler** [comment]
+1 agree!

**Comment by SecurityCRob** [comment]
+1

**Comment by balteravishay** [comment]
+1

**Comment by ran-dall** [comment]
`+1`

**Comment by drusso-rh** [comment]
+1 agreed!

Are there other working groups that this SIG could potentially "collide" with? If so, we might want to proactively engage with them to avoid competing efforts or duplicate work.

**Comment by JLLeitschuh** [comment]
(voting member): +1

**Comment by xcorail** [comment]
+1 👍🏾

**Comment by laurentsimon** [comment]
+1

**Comment by lehors** [comment]
+1

**Comment by nellshamrell** [comment]
@drusso-rh  I don't know of any that we would collide with, but we are certainly willing to work with any of them!

**Comment by scovetta** [comment]
@drusso-rh It doesn't collide with Identifying Security Threats, and I don't think it collides with any others.

**Comment by SecurityCRob** [comment]
**Summarizing**: 11 working group members have expressed their approval to adopt this project as a SIG underneath our working group. 

We will move forward and inform the TAC formally about this new SIG and the group's desired path forward. Thank you to everyone that participated in this conversation, and we look forward to everyone continuing to collaborate as we move forward.
