### ISSUE TITLE
Compiler Hardening Guide:  `-Wl,-z,noexecheap` command-line option

### ISSUE THREAD

**Issue by rcseacord** [ossf/wg-best-practices-os-developers#148]
The `-Wl,-z,noexecheap` command-line option is not supported by gold or lld [12.0.0](https://releases.llvm.org/12.0.0/tools/lld/docs/ReleaseNotes.html).

It's an interesting question if we should be recommending options that aren't very portable.  At the very least, we should be more specific about where this is supported.  Binutils isn't very helpful since 50% of the linkers don't work.

**Comment by siddhesh** [comment]
As an aside, gold is largely unmaintained, so we should probably target only `lld` or `ld.bfd`.  `noexecheap` however looks like a Gentoo extension; it's not present in any of the upstream toolchains.  I'll work on some text to fix this.

**Comment by thomasnyman** [comment]
PR https://github.com/ossf/wg-best-practices-os-developers/pull/154 addresses the specific concern with `-Wl,-z,noexecheap`.

I agree that we should aim to be precise with the attributing the different options to specific compiler / linker versions.
Currently we are still missing version information for the `-rpath` options under the discouraged compiler options. 
I assigned myself a separate issue to fix this (https://github.com/ossf/wg-best-practices-os-developers/issues/164) but in general, should we also make distinction between GNU `ld`, `ld.bfd` and LLVM `lld` when attributing linker options or is is sufficient to separate between Binutils version and LLVM version?

**Comment by thesamesam** [comment]
> As an aside, gold is largely unmaintained, so we should probably target only `lld` or `ld.bfd`. `noexecheap` however looks like a Gentoo extension; it's not present in any of the upstream toolchains. I'll work on some text to fix this.

Quite an old one too, I think. We dropped that a long time ago.
