### ISSUE TITLE
Modify pages to use the best.openssf.org site, if we decide to switch to it

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/wg-best-practices-os-developers#161]
If we like the bp.openssf.org site & think it's ready, we should modify various pages to use it (e.g., link to it).

**Comment by ctcpip** [comment]
prefer to avoid an acronym, especially where overloaded and not common.  is an alternative possible?  e.g. `best.openssf.org` ?

**Comment by david-a-wheeler** [comment]
We could do that.

That's not really the point of this issue, though. I suggest creating new issue so we can discuss naming as its own topic.

Until that new issue is created, let me quickly comment. Domain names are often best short so it's easy to se what it is. The WG discussion today accepted "bp.openssf.org" so that's what I set up. That said, it would be easy to change, and now is the time to change it (if we change).

**Comment by ctcpip** [comment]
will do -- I couldn't attend today, so was missing context.  thanks

**Comment by david-a-wheeler** [comment]
The generated pages are now working at best.openssf.org, with https: (TLS) enabled. Also: if you prefer, you can omit the trailing ".html". You can try it out here:

* https://best.openssf.org/Concise-Guide-for-Evaluating-Open-Source-Software
* https://best.openssf.org/Concise-Guide-for-Developing-More-Secure-Software

These pages are using the draft OpenSSF font recommendations (those can be changed if desired).

**Comment by david-a-wheeler** [comment]
I would like to modify https://openssf.org/resources/guides/ to use these new URLs. We can always improve the generated pages' looks, but they *already* look better than what we're doing now, and if we point people to the "right" URL then people will start using the new URLs.

Agree or disagree?

**Comment by david-a-wheeler** [comment]
This is done.
