### ISSUE TITLE
CII Best Practices badge: Improved mechanisms to see badges

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/wg-best-practices-os-developers#18]
FYI, CII Best Practices badge has a new mechanism to make it easier to integrate in to dashboards:
https://github.com/coreinfrastructure/best-practices-badge/issues/1460

You can easily see the passing criteria here:
https://bestpractices.coreinfrastructure.org/criteria/0

**Comment by RedHatCRob** [comment]
Having spent 12+ hours developing our own matrix for this earlier this year let me express this is a very nice evolution.  I wish I had waited for you all to update this, would have saved me SO much time!

**Comment by david-a-wheeler** [comment]
@RedHatCRob - I'm glad it helped! If there's something else that would really help you, let us know. Issues and pull requests welcome!

**Comment by torgo** [comment]
Can we close this off?

**Comment by torgo** [comment]
agreed to close in meeting 11-oct
