### ISSUE TITLE
Suggestions on Concise Guide for Evaluating Open Source Software

### ISSUE THREAD

**Issue by AndrewX192** [ossf/wg-best-practices-os-developers#202]
I recently came across the [Concise Guide for Evaluating Open Source Software](https://best.openssf.org/Concise-Guide-for-Evaluating-Open-Source-Software)! Really glad to see people talking about this topic. In my past experience I've seen a few other areas that I believe are important to this evaluation. Happy to open a pull request but thought I'd field some thoughts on the direction you'd like this page to take first, given that there's a competing goal to be concise :) Most of these are focused more around how software is to be used rather than the posture of the software on it's own as I've found those to be a bit more valuable than considering a piece of software at a particular point in time:

1) How do you intend to use the software? Is it a build or runtime dependency? Will the software be incorporated into a versioned deliverable to users or up for the user to update themselves? Pay attention to not only how you would update the software in your latest build particularly where your use case is a mobile or desktop application.
- In the case that you only need some functionality of the software it may be helpful to understand the code structure in detail and only utilize specific portions of the software (e.g. classes, packages, modules, etc.) to solve your problem rather than the entirety of the software.
- If you only need the software for a debug / pre-release or as part of the build process ensure it isn't being utilized as a runtime dependency
2) How will you become aware of updates to this software? Are there regular releases or only a mainline branch? How will you approach updating this software (every version, minor only, etc?)
- If you are a significant user/contributor of this of software you may want to consider pre-release (embargoed) notice of future updates you can be ready to update.
3) Should a vulnerability be discovered, what can you to stop immediate bleeding? Can you degrade features, or disable functionality entirely?
- Consider implementing configuration options or other means of disabling functionality supported by this software if possible.
- In the event that a user is responsible for updating the dependency outside of your system, consider warning mechanisms to alert the user of out of date dependencies.
- If the software is not distributed together, consider emitting information about the version of any dependencies at startup so that the user can easily understand what version(s) were picked up and whether a particular runtime instance might be vulnerable.
4) What happens if the software becomes unmaintained? Are there alternatives you could switch to? Could you take on maintenance of the open source project? 
- It may be valuable to attempt to spend some time understanding the software and making some basic modifications to prepare for the potential to need to need to maintain this software on your own.
5) What will you do if the software does not meet a requirement of your software (e.g. scale, durability, etc.)?
- Your use-cases may not be amendable to the maintainer's aspirations for the project. Will you need to fork the software? If so, how will you ensure that your fork will not devolve far from the upstream's development progress?

Again, happy to iterate on this a bit more but more interested in your thoughts around the topic areas and potential to include them in such a guide?

**Comment by AndrewX192** [comment]
Will do. I'm going to take some time to think through a more complete guide here as the above are some immediate things that come to mind that I've personally used or encouraged others to consider. There are probably a few more things that I'd want to add after some more thought.

One general open question at this point. The focus of my evaluation questions is more around how a developer intends to make use of the open source software rather than evaluating the software itself. Structurally I'd like to fit as many items alongside others in the current list (e.g. "how will you become aware of updates"), but some of the other items are very use-case specific and are things we might want to emphasize a little differently. 

Specifically, I'm thinking about situations where a user of this guide might evaluate an open source project once and use it for many purposes and might overlook something important. For example the update rollout process of a mobile or desktop application with many users and a backend application managed by a few engineers is going to have significant timeliness differences that might warrant developing controls around (see previous remarks around "stop immediate bleeding").

Are there any particular thoughts around how the working group would want to structure use case related questions v.s. general evaluation questions? If not I'm happy to propose something once I've had some time to flush out a more complete criteria.

**Comment by david-a-wheeler** [comment]
> Will do. I'm going to take some time to think through a more complete guide...

This guide is supposed to be concise. If you have a *lot* of detail, I suggest creating a brief summary, then create a longer document with the "more complete" details for us to link to.

**Comment by ware** [comment]
> > Will do. I'm going to take some time to think through a more complete guide...
> 
> This guide is supposed to be concise. If you have a _lot_ of detail, I suggest creating a brief summary, then create a longer document with the "more complete" details for us to link to.

This would seem to be a good direction.  Concise directions that cover the ~80% of cases and additional detail guiding for everything else.

**Comment by AndrewX192** [comment]
Several months have gone by since I opened this PR and unfortunately I am no longer able to contribute to Linux Foundation projects due to employment constraints. Seeing as there’s very little if anything to change I’ll go ahead and close out this PR and related issue as WONTFIX.
