### ISSUE TITLE
Scorecard roadmap review 

### ISSUE THREAD

**Issue by afmarcum** [ossf/wg-best-practices-os-developers#205]
Please review [the Scorecard roadmap](https://docs.google.com/document/d/1ttLH1U4BRZkgVukBltLxKyP7UmFSLIyPtUUe1G86Sv0/edit?usp=sharing) for feature work through the end of the year and provide feedback.

**Comment by ware** [comment]
@afmarcum, when do you optimally need feedback?

**Comment by afmarcum** [comment]
> @afmarcum, when do you optimally need feedback?

@ware within the next week, ideally, before the next Scorecard/Allstar sync.

**Comment by afmarcum** [comment]
Thank you for the roadmap feedback. All items appear to have been addressed so considering this issue closed. Please reopen if something more is needed.
