### ISSUE TITLE
[VOTE] APAC/Pacific TZ version of the BEST Working Group

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/wg-best-practices-os-developers#206]
Hello friends!  I am seeking feedback from all active WG members(https://github.com/ossf/wg-best-practices-os-developers/blob/main/members.md).  The Scorecard team has requested we consider some meeting alterations to allow them to more directly collaborate with the larger working group.  Please let us know your preference around the following two options:

A) Begin alternating BEST WG meeting times between the current time, and then an APAC/PT-friendly time.  This would mean that unless folks go to both geo meetings, that there would potentially only be one WG call each month in your TZ

B) Create a new additional monthly meeting for the APAC/PT folks so they can interact more officially with the larger WG.

Depending on which option is selected by the group, we'll send out a Doodle poll to zero in on that meeting's time/day based on those who desire to participate.  Please comment here and ultimately express your vote on which option you prefer by our next WG call 15August.  Thanks all!

**Comment by ctcpip** [comment]
it's difficult to take a position on this without knowing what times we are talking about.  presumably the existing time is reasonable for folks in India.  that said, if APAC-friendly means being inclusive* with e.g. East Asia

presuming a window of a meeting that starts between UTC 00:00 and UTC 04:00:

| Earlier start time | Later start time | TZ               |
| ------------------ | ---------------- | ---------------- |
| 17:00              | 21:00            | Pacific US       |
| 18:00              | 22:00            | Mountain US      |
| 19:00              | 23:00            | Central US       |
| 20:00              |                  | Eastern US       |
| --- next day ---   | --- next day --- | --- next day --- |
|                    | 00:00            | Eastern US       |
| 00:00              | 04:00            | UTC           |
| 08:00              | 12:00            | China            |
| 09:00              | 13:00            | Japan            |
| 10:00              | 14:00            | Melbourne        |
| 12:00              | 16:00            | Auckland         |

but if we don't, at this time, need to include* East Asia, and instead optimize only for, e.g. Australasia and PT, then we have earlier possibilities:

| Earlier start time | TZ               |
| ------------------ | ---------------- |
| 15:00              | Pacific US       |
| 16:00              | Mountain US      |
| 17:00              | Central US       |
| 18:00              | Eastern US       |
| 22:00              | UTC              |
| --- next day ---   | --- next day --- |
| 08:00              | Melbourne        |
| 10:00              | Auckland         |

so for these examples, I would say if we were trying to optimize for the former table (inclusive* of East Asia), then I would lean toward Option B: a new monthly meeting.  but if including* East Asia was not a goal here, then I would lean toward option A: alternating, as the times are (potentially) still reasonable for US timezones.

*of course, we don't intend to exclude _anybody_, but we need to be pragmatic about the actual folks who are attending and what timezones we need to account for _at this time_.

**Comment by caabernathy** [comment]
I've even seen EMEA / APAC friendly times that start in the 1 - 4 AM US EST times. [Planning example below](https://www.timeanddate.com/worldclock/meetingtime.html?iso=20230803&p1=136&p2=44&p3=240&p4=179&p6=234)

For APAC / PT I've seen 3-6 PM PT start times.

![Screenshot 2023-08-01 at 8 27 49 PM](https://github.com/ossf/wg-best-practices-os-developers/assets/691109/6cfb5f5e-d765-4d2a-b67f-041d298fa54b)

I would go with Option B but I've no idea which combo would work best - EMEA+APAC or APAC+PT.

**Comment by SecurityCRob** [comment]
In the haste of my busy day yesterday, I perhaps used and overly strong word in "vote".  I'm seeking to see interest in the group in better collaborating with our Scorecard team, who are PT TZ.  Typically times that are good for California et. al. will have OK overlap with Australia and some into Eastern Asia.  We've got 490 folks lurking in the slack channel and many more on the mailing list than attend the regular EMEA-ET TZ call today, so I'm trying to afford anyone interested in participating that opportunity.  The call ultimately would be determined based off of who wants to participate, but it would be good to know if any existing "regulars" are open to joining a new call to welcome new friends and to give us a chance to work with our Scorecards pals.

**Comment by laurentsimon** [comment]
I'll vote for 3+ PM PST time, which is friendly to the West USA and countries like Australia, Japan, etc

**Comment by SecurityCRob** [comment]
@BEST - is there enough interest/participants that would attend an "APAC-friendly" TZ call?

**Comment by SecurityCRob** [comment]
There was insufficient interest in spawning off another call at this time.  Closing for now until we get critical mass of folks interested in participating at alternate times.
