### ISSUE TITLE
[VOTE] - Adoption of Sterling Toolchain/Security Toolbelt SIG within the BEST WG

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/wg-best-practices-os-developers#207]
Team - there is need to find a more permanent home for the SIG formerly known as "the Sterling Toolchain"(1) (now known as the Security Toolbelt).  This effort is seeking to identify patterns, architectures, automated tooling, and signals that help impact security across the open source supply chain.  We're curious if this could find a home nestled within the warm and loving embrace of our BEST practices community?  Please review the materials, express your thoughts and ultimately please let us know if you feel this could be a match to report up through our group.  I'd like to hear from our active members (https://github.com/ossf/wg-best-practices-os-developers/blob/main/members.md) before our next call on 15Aug please.

(1) - https://github.com/ossf/Diagrammers-Society/tree/main/SecurityToolbelt

**Comment by ctcpip** [comment]
I'm not opposed, but I wonder if this might be more germane to the Security Tooling WG?

**Comment by caabernathy** [comment]
I'm good with it given it's tackling best practices around the consumption and development of open source software. It initially reads to me like an expansion of the concise guides.

**Comment by gkunz** [comment]
I am fine with adopting this work into the best practices WG, however, I wouldn't oppose if another WGs makes a good case for adopting it.

**Comment by sevansdell** [comment]
Although it's not a strong opinion (I could easily go with BEST practices too), the security tooling WG makes sense to me. TOOLbelt, TOOLchain, security TOOLS. Closing gaps and automating tooling is more than a best practice, it's going to be an integration that makes best practices easier.

**Comment by lehors** [comment]
I think this should really go to the Tooling WG. If it doesn't I don't know what the Tooling WG is for.

**Comment by gkunz** [comment]
In general, I think either home is fine, in particular as the (current) scope of the Security Toolbelt also includes guidelines and best practices.

Nevertheless, placing it under the Security Tooling WG indeed has several advantages: It makes sense from a terminology perspective as already pointed out. But it also expands the scope of the Security Tooling WG beyond its current focus on SBOM (SBOM Everywhere stream) - which in itself of course is absolutely fine (focus is good). But from the perspective of an outside observer of the OpenSSF, a broader Tooling WG would be great.

In practical terms, it is "just" a label as the people interested in working on this topic will do it under any WG - I assume and hope.

Still, we should make the Security Tooling WG folks aware of our conversation here to not just talk about - but with them. So, adding @joshbressers.

**Comment by ctcpip** [comment]
My hope is that it will make little/no substantive difference where the SIG lands.  I expect folks from both the tooling and best practices working groups to participate.

**Comment by ware** [comment]
> My hope is that it will make little/no substantive difference where the SIG lands. I expect folks from both the tooling and best practices working groups to participate.

I would agree with this.  That said, if it ends up in the Tooling WG, I can help better there as I have less conflicts to attending.  It would also be nice for the Tooling WG to have something other than SBOM Everywhere.

**Comment by lehors** [comment]
I appreciate the practical aspect of calendaring issues but I don't think this should be the driving factor here. For that matter the Security WG meetings have been taken over by the SBOMs Everywhere SIG so a new time slot could be used for the WG meetings.

**Comment by lehors** [comment]
So, for the record, the Security Tooling WG is currently in limbo having been taken over by the SBOM Everywhere SIG and @joshbressers saying he has no interest in leading the WG anymore. This is an issue the TAC will need to deal with but it will take time. For that reason I'm supportive of the Best Practices WG adopting the Toolbelt SIG at this time.

**Comment by SecurityCRob** [comment]
The Toolbelt group discussed this issue on our 15Aug call and were in agreement that the BEST WG would be a fine place to be homed at this point.  If there are objections prior to EoD tomorrow, I'll work with staff to connect the dots and note that Toolbelt is supported by this WG.

**Comment by SecurityCRob** [comment]
The Toolbelt team agreed that BEST would be a dandy place to be homed on their 15Aug call.

**Comment by SecurityCRob** [comment]
Hearing no dissenting views nor viable alternate suggestions, the Toolbelt will be homed here in the BEST WG.  Thanks to everyone that shared their thoughts.
