### ISSUE TITLE
Formatting errors in Compiler Options Hardening Guide for C and C++

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/wg-best-practices-os-developers#210]
The "Compiler Options Hardening Guide for C and C++" still has a few formatting problems, even after #209. There aren't many, but they detract from the awesome content.

1. Just after table 2 and just before "Enable warnings for constructs often associated with defects" is this odd thing:

~~~~
https://developers.redhat.com/blog/2020/02/11/toward-_fortify_source-parity-between-clang-and-gcc and Poyarekar, Siddhesh. D91677 Avoid simplification of library functions when callee has an implementation. (LLVM Phabricator) https://reviews.llvm.org/D91677
~~~~

2. Just after this note there are some isolated URLs: "NOTE: Despite its name the -Wall options does NOT enable all possible warning diagnostics, but a pre-defined subset. For a complete list of specific warnings enabled by the-Wall and -Wextra compiler please consult the GCC12 and Clang13 documentation respectively."

3. Similarly, just before "Mark relocation table entries resolved at load-time as read-only" there are some isolated URLs.

**Comment by gkunz** [comment]
Thanks @david-a-wheeler for spotting this.

Question to the crowd: I'd actually like to make use of inline links in the footnotes, rather then just adding the URL. An example is [this change](https://github.com/ossf/wg-best-practices-os-developers/pull/211/files#diff-98ef1dcd57c9c3922c1edda5cfc0c2726b1c2a3e32a7c517e9e0801d5f4270cbR159). Let me know if you'd like to see those changes or prefer to keep the current layout.

**Comment by ware** [comment]
> Thanks @david-a-wheeler for spotting this.
> 
> Question to the crowd: I'd actually like to make use of inline links in the footnotes, rather then just adding the URL. An example is [this change](https://github.com/ossf/wg-best-practices-os-developers/pull/211/files#diff-98ef1dcd57c9c3922c1edda5cfc0c2726b1c2a3e32a7c517e9e0801d5f4270cbR157). Let me know if you'd like to see those changes or prefer to keep the current layout.

I wouldn't have an issue with it but don't know how well it complies with other documents OpenSSF is generating.
