### ISSUE TITLE
Need to select new Co-Lead 

### ISSUE THREAD

**Issue by afmarcum** [ossf/wg-best-practices-os-developers#220]
I am not sure what the selection process is and want to know how I can help.

Similar question for the Backlog Warden. Please let me know I need to create a separate issue for each role.

**Comment by afmarcum** [comment]
Apologies for the delay on this, but here is a draft of WG Lead responsibilities. Let me know whether a separate issue is required for approving these specifically or if submitting in a PR to add to official WG documentation works.

**WG Lead Roles & Responsibilities**

- Facilitate WG meetings including agendas, calls for topics, and capturing and following up on action items
- Drive progress on WG efforts whether specifications, code, or other contributions 
- Provide technical guidance and sponsorships for sub-projects and arbitrate technical disputes
- Present WG updates to TAC
- Facilitate WG voting as needed
- Accountable for GitHub Repo management including edits/updates, issue and PR backlog management, and delegating responsibility to a separate volunteer, if applicable
- Time commitment: 1-2 hours per week

**Comment by ran-dall** [comment]
This issue has been addressed in PR #361. I apologize for not linking the issue initially. Closing.
