### ISSUE TITLE
Proposal to Archive - Great MFA distribution SIG

### ISSUE THREAD

**Issue by afmarcum** [ossf/wg-best-practices-os-developers#232]
Based on "Application for archiving of a project" in the Project Lifecycle Process because the
process has not been defined for SIGs or WGs.

**Reasons for archiving:**
This SIG appears to have successfully completed its mission. There are limited tokens remaining (which were donated) and the effort to distribute was resource intensive. The repo has been archived and there is no group meeting. The slack has had no communication in the last 90 days. 
[Great MFA distribution SIG](https://github.com/ossf/great-mfa-project)

Please review and inform the project maintainers, OpenSSF end user community and wider community of this archiving proposal. The proposal must remain open for at least 2 weeks of discussion after the maintainers are informed and a vote must be finalized with 2/3 approval from the TAC or parent WG to complete the archive process.

**Comment by SecurityCRob** [comment]
I am fine with this cleanup

**Comment by ran-dall** [comment]
This issue was discussed today in the BEST WG.

```
WG agrees that MFA is archived. We accomplished a lot, 2FA is now more common, we’re moving on.
```
