### ISSUE TITLE
Compiler Hardening Guide should recommend `-fhardened` option

### ISSUE THREAD

**Issue by thomasnyman** [ossf/wg-best-practices-os-developers#240]
> Soon the Best Practices guide should recommend the newly proposed `-fhardened` option:
[patch and thread](https://gcc.gnu.org/pipermail/gcc-patches/2023-August/628748.html)

_Originally posted by @edelsohn in https://github.com/ossf/wg-best-practices-os-developers/issues/234#issuecomment-1722058275_

**Comment by thomasnyman** [comment]
This was discussed during the [C/C++ Compiler BP Call 2023-09.27](https://docs.google.com/document/d/1UClGUnOSkOH_wab6Lx43KUdkaK37L8sbWJ_GPZvc1YY/edit#bookmark=id.863n4hp4nw9q).

The proposed`-fhardened` flag seems like a good addition to the guide but given that it's currently targeting GCC 14 (expected in May 2024) the overall consensus among the participants to the discussion was to postpone its addition until it is available in an official GCC release.

In the meantime, as `-fhardened` is an 'umbrella option' that enables a set of flags already available in current GCC (and Clang) releases the constituent options not yet covered by the guide can be considered already now.

I've opened issues #245 and #247 for `-ftrivial-auto-var-init` and `-fcf-protection` respectively.

Leaving this issue open to track `-fhardened` as the discussion around the functionality stabilizes in the GCC community.

**Comment by SecurityCRob** [comment]
Has this been addressed by the C/C++ Compiler Hardening options guide?    @gkunz @thomasnyman @david-a-wheeler

**Comment by thomasnyman** [comment]
@SecurityCRob Yes, this is being worked on in #492 now that GCC 14 has been released.
