### ISSUE TITLE
Compiler Hardening Guide should include -fcf-protection

### ISSUE THREAD

**Issue by thomasnyman** [ossf/wg-best-practices-os-developers#247]
Brought up during the [C/C++ Compiler BP Call 2023-09.27](https://docs.google.com/document/d/1UClGUnOSkOH_wab6Lx43KUdkaK37L8sbWJ_GPZvc1YY/edit#bookmark=id.863n4hp4nw9q).

The `-fcf-protection=[full|branch|return|none|check]` enables the instrumentation of control-flow transfers to ensure that target addresses of indirect control-flow transfer instructions (such as indirect function calls, function returns, and indirect jumps) are within a statically or dynamically determined set of possible targets. This is intended to protect against threats as [Return-oriented Programming](https://hovav.net/ucsd/papers/s07.html) (ROP), and similarly [call/jmp-oriented programming](https://www.comp.nus.edu.sg/~liangzk/papers/asiaccs11.pdf) (COP/JOP).

This flag is supported since [GCC 8.0](https://gcc.gnu.org/gcc-8/changes.html) and [Clang 7.0.0](https://releases.llvm.org/7.0.0/tools/clang/docs/UsersManual.html#command-line-options).

## Considerations and references

- [GCC documentation](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fcf-protection) 
- Currently only supports x86 processors with [Intel Control-Flow Enforcement](https://www.kernel.org/doc/html/next/x86/shstk.html) (CET) or [AMD Shadow Stack](https://www.phoronix.com/news/Shadow-Stacks-Linux-AMD) hardware features
- [Kernel support for userspace x86 shadow stack added in Linux 6.6](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=df57721f9a63e8a1fb9b9b2e70de4aa4c7e0cd2e)
- [Requires glibc 2.28 or later](https://sourceware.org/legacy-ml/libc-alpha/2018-08/msg00003.html)
- [Potential ABI compatibility issues in applications that manage their stacks in ways which do not conform with shadow stack expections](https://lwn.net/Articles/885220/)

**Comment by thesamesam** [comment]
See also https://github.com/ossf/wg-best-practices-os-developers/issues/267.

**Comment by thomasnyman** [comment]
Fixed by #260.
