### ISSUE TITLE
Update description field in .github/settings.yml

### ISSUE THREAD

**Issue by kaywilliams** [ossf/wg-best-practices-os-developers#25]
@xcorail 

We will be using the description listed in the .github/settings.yml for each project to create a summary list for the [OpenSSF website getting started page](https://openssf.org/join/) and an upcoming press release. Please edit the description field to include a short (1-2 sentence) description. Due Date - Thursday 10/8/2020

See example here:
https://github.com/ossf/gb-planning-committee/blob/master/.github/settings.yml

**Comment by xcorail** [comment]
@kaywilliams proposal in this PR: #27
