### ISSUE TITLE
Add -mshstk to the C/C++ Compiler Hardening Guide?

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/wg-best-practices-os-developers#267]
I think we should consider adding `-mshstk` to the C/C++ Compiling Hardening guide.

It is recommended in [Use compiler flags for stack protection in GCC and Clang](https://developers.redhat.com/articles/2022/06/02/use-compiler-flags-stack-protection-gcc-and-clang#safestack_and_shadow_stack), where it notes: "This form of protection splits the stack into two distinct areas, storing precious variables and user variables in non-contiguous memory areas. The goal is to make it more difficult to smash one of the stacks from the other. This process occurs in hardware (e.g., x86_64 shadow stack) or in software such as LLVM's SafeStack."

This `-mshstk` flag is supported in clang and GCC. [GCC 9.1.0 documents](https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/x86-Options.html) it as follows: "The -mshstk option enables shadow stack built-in functions from x86 Control-flow Enforcement Technology (CET)."

I'm not recommending adding Clang's SafeStack, which it adds through this flag: `-fsanitize=safe-stack`. [This StackOverflow answer](https://stackoverflow.com/questions/39371514/stack-protect-equivalent-in-clang-compiler) suggests there are problems with that with shared libraries. That may be incorrect (please let me know!), but until we're confident that problems are rare, I'm not confident in recommending it.

**Comment by thesamesam** [comment]
The distinction between `-fcf-protection` and `-mshstk` is poorly covered in compiler documentation which doesn't help.

For our Hardened profiles in Gentoo, we pass `-fcf-protection` at least.

**Comment by thomasnyman** [comment]
The built-in functions are, in my opinion, only needed if you are building a shadow stack support into C standard libraries or other code which may be doing unconventional management of the stack. 

I would suggest we cover `-mshstk` in the _Considered Compiler Options_ table (for completeness) but recommend `-fcf-protection`.
