### ISSUE TITLE
malloc_usable_size incompatible with _FORTIFY_SOURCE=3

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/wg-best-practices-os-developers#278]
Some applications use malloc_usable_size (despite the glibc manual stating it is for diagnostic purposes only). This is currently incompatible with _FORTIFY_SOURCE=3. This should be documented in the compiler options guide.

https://archlinux.org/todo/prepare-packages-for-d_fortify_source3/

**Comment by david-a-wheeler** [comment]
It's good that some code is fixed. However, since it's a common problem, I think we should mention it in the guide.

**Comment by siddhesh** [comment]
Oops, looks like @david-a-wheeler won that race 😃 

I like your direct suggestion to remove the use of `malloc_usable_size`.  Could you also please incorporate the idea that using `realloc` to expand to the usable size should also work?  That's a pretty quick operation now with glibc `malloc`.
