### ISSUE TITLE
In C/C++ hardening guide discuss instrumented test code vs production code

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/wg-best-practices-os-developers#298]
There seems to be a confusion between instrumented test code and production code.

When running software in production, you should use production code.

However, when testing, it is sometimes more complex. You typically want to test the production code, so that what you test is what you ship. However, if you only test the production code, you may miss some important problems. So it is often helpful to also generate executables that are especially introduced to warn about problems that would not be obvious in the production code version. I think that is the basis of some of the odd comments that some options shouldn't be used in production because they will make production code more reliable. Of course you want production code to be reliable!

I suggest adding a short section to describe the distinctions between these 2 kinds of executives. that will set up explaining the different options for the different situations.

**Comment by david-a-wheeler** [comment]
On 2023-11-22 there was agreement in principle, need to work out text.

**Comment by Flo4152** [comment]
I've tried to focus on this issue and formalize some of the differences between production and test code.

I think at these two kind of production code :
- Compiled binaries distributed as final product (closed source)
- Tarball distributed as an archive for installation (ready to be compiled by end-users -> open source or restricted source): source + makefile

Production codes are projects already published: Already tested in previous phases (source code validation, benchmark, etc.) :
- Open source or restricted source : Makefile includes only finals compilation flags: Security features to be included in final binaries (source code validation is out of scope, as already performed in previous testing phases).
- Compiled binaries: No compilation flags required and binary analysis already performed in previous testing phases (bugs/crash during production are mainly reported to maintainers/packagers for them to open a testing phase).

A production code have these main characteristics:
- Availability must reach 100% of production time.
- Requested processing must deliver expected performance (close to benchmark results).
- Certified confidentiality: User data must be protected against theft (leaks).
- Guaranteed integrity of requested processing: The result is in line with expectations.
- Clear and definitive safety features in the final binary with minimal impact on expected specifications:
   - The binary must ensure sanitization of inputs from the user context (direct inputs, input files, system interrupts [user-controlled device: usb stick, remote device (bluetooth, wifi, etc...), etc...], etc...).
    - Ensure execution control flow.
    - Detect memory corruption.
    - etc.
 
Security features can be added to binaries during the compilation process (stack protection, access rights to memory segments, address space randomization/code position independence, etc.). I hope to add more details about it in a next post.

Regards,

Florian
