### ISSUE TITLE
CII Best Practices work

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/wg-best-practices-os-developers#3]
The CII has been doing work for years in developing & refining a set of best practices for developing secure open source software. [Over 3,300 projects are participating](https://bestpractices.coreinfrastructure.org/en/project_stats).

I'd be happy to talk about it at length. Some URLs:

* [CII Best Practices Badge Program (website for getting a badge)](https://bestpractices.coreinfrastructure.org/)
* [Criteria for "passing" level (with rationale)](https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md)
* [Criteria for silver & gold](https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/other.md)
* [GitHub repo for CII Best Practices](https://github.com/coreinfrastructure/best-practices-badge)

**Comment by xcorail** [comment]
👋🏾 @david-a-wheeler 
Would you be willing to join the working group next meeting (Monday 31st, 8am PST) and discuss?

**Comment by xcorail** [comment]
Invite to participate to the working group send. Looking forward to it!

**Comment by david-a-wheeler** [comment]
I'll be there on the 31st. I'd be happy to discuss:

* the CII Best Practices badge (presentation here)[https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/cii-bp-badge-intro.pptx]
* the "developing secure software" course that I've drafted, [as noted here](https://github.com/ossf/wg-best-practices-os-developers/issues/11)
