### ISSUE TITLE
Clarify why -O2

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/wg-best-practices-os-developers#331]
There's no separate entry for `-O2` in the hardening guide. We should add one. In particular, it doesn't *have* to be `-O2`, `-O3` is also fine. The reason for at least level 2 is that some of the other hardening mechanisms require it. We document that in their own points, but I think there also needs to be a short discussion about `-O` all by itself.

**Comment by SecurityCRob** [comment]
Has this been addressed by the C/C++ Compiler Hardening options guide?    @gkunz @thomasnyman @david-a-wheeler

**Comment by thomasnyman** [comment]
Some restructuring of the optimization options happened as a result of #490. Closing after review in [Compiler BP Call 2024-06-27](https://docs.google.com/document/d/1JY8FREBPCUUFpuv7-4B9EjeS2MLDpel0dbG5DFWrTns/edit#bookmark=id.dhr32hb9yx35).
