### ISSUE TITLE
tl;dr section suggests options that it maybe shouldn't

### ISSUE THREAD

**Issue by AaronBallman** [ossf/wg-best-practices-os-developers#333]
Clang doesn't support `-Wtrampolines` and will diagnose it as an unknown warning option, so it might not make sense to include it in the tl;dr section (I would expect some people will copy/paste that section without giving it much thought).

Also, `_FORTIFY_SOURCE` support differs between Clang and GCC (https://developers.redhat.com/blog/2020/02/11/toward-_fortify_source-parity-between-clang-and-gcc) and those differences should be called out explicitly in the tl;dr so people don’t get a false sense of security with the option.

**Comment by david-a-wheeler** [comment]
We now have a table showing "if condition X, use option Y". I think it's fine to have a gcc-specific entry (or a clang-specific entry) if an option is supported by one but not the other.
