### ISSUE TITLE
-Wformat=2 vs -Wformat

### ISSUE THREAD

**Issue by AaronBallman** [ossf/wg-best-practices-os-developers#334]
In Clang, `-Wformat` (https://github.com/llvm/llvm-project/blob/c7b3ae5ab9c8ffc19db00bd6e995d225ac1013e9/clang/include/clang/Basic/DiagnosticGroups.td#L978) includes more useful diagnostics than `-Wformat=2` (https://github.com/llvm/llvm-project/blob/c7b3ae5ab9c8ffc19db00bd6e995d225ac1013e9/clang/include/clang/Basic/DiagnosticGroups.td#L984). It might make sense to consider suggesting `-Wformat` because it includes the same diagnostics as `-Wformat=2` as well as many other more problematic situations (like invalid specifiers, insufficient number of args, overflow, etc).

**Comment by david-a-wheeler** [comment]
* [Clang Documentation](https://clang.llvm.org/docs/DiagnosticsReference.html#wformat) https://clang.llvm.org/docs/DiagnosticsReference.html#wformat
* See gcc: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
* Unfortunately this appears to be an unintentional divergence between gcc and clang.
* Possible solution: “-Wformat -Wformat=2”. Adding the second option would make the first option a no-op in gcc, but might add the options desired in clang. We need to test this.

**Comment by thomasnyman** [comment]
Test case for the difference between `-Wformat`, `-Wformat=2`, and `-Wformat -Wformat=2`: https://godbolt.org/z/Mvze5boq7

The outcome is that `-Wformat=2`is redundant in Clang if `-Wformat` is already specified, whereas `-Wformat` is redundant in GCC if `-Wformat=2` is already specified, but the combination `-Wformat -Wformat=2` still works for both compilers.
