### ISSUE TITLE
Should there be a "what should you do when compiling compilers" section at all?

### ISSUE THREAD

**Issue by AaronBallman** [ossf/wg-best-practices-os-developers#335]
Users don’t compile their compiler, generally speaking. So having this section is a bit surprising. But also, the section is pretty sparse in terms of its advice. Perhaps it makes sense to remove the section rather than expand it? Folks packaging applications for distros are basically the only target audience I can think of for this section, and they’ve already got their own best practices that will depend on the distro, I suspect.

**Comment by jbmaillet** [comment]
> Folks packaging applications for distros are basically the only target audience I can think of for this section

...and folks doing their own toolchains for the billions of embedded devices all around us (and in my 23+ years of industrial embedded OSS, vendor toolchain use is actually a very rare case, and rarest and rarest as time passes, with the noticeable exception of Android).

**Comment by jbmaillet** [comment]
I am not sure this use case is so special compared to regular toolchain's creation for regular Linux distributions. The only things I can think of, from the top of my head:

- Intel x86 / AMD64 are not the typical architectures here: ARM and ARM64 dominate the field, then MIPS, then maybe RISC-V could be useful. As far as I know, PowerPC is only used in the military and aerospace sectors.
- The lib is not necessarily the GNU libc, it can be musl has well.

I don't create toolchains myself (some colleagues of mine do). It could be interesting to have a look at what embedded build systems such as Buildroot and Yocto use, since they build their cross-compiler and libc from scratch.

**Comment by jbmaillet** [comment]
> I'm not sure there's much more that could be added. For the most part there aren't a lot of _special_ knobs when compiling the _compiler_ (as opposed to using the compiler executable to compile something else). So it's not really worth creating a separate document. Also, if we create a _separate_ document, there's a risk it'll never be read. So I prefer the current arrangement, unless we have a lot of added material we can add for this case.

Fair enough.

**Comment by AaronBallman** [comment]
> I'm not sure there's much more that could be added. For the most part there aren't a lot of _special_ knobs when compiling the _compiler_ (as opposed to using the compiler executable to compile something else). So it's not really worth creating a separate document. Also, if we create a _separate_ document, there's a risk it'll never be read. So I prefer the current arrangement, unless we have a lot of added material we can add for this case.

I think this depends on what reason you're compiling the compiler. If you're making a compiler for an embedded platform and you control the distribution of the compiler, that's a very different security profile than if you're compiling a compiler because you're going to host it as a web service (like Compiler Explorer, IDE One, Wandbox, etc), or if you're compiling a compiler for general distribution. That's why I still don't think this section makes much sense in this particular document.

**Comment by thomasnyman** [comment]
I believe we did discuss at one point featuring the "what should you do when compiling compilers?" section as an appendix. That might be a good option as well in light of this feedback. 

> I'm not sure there's much more that could be added. For the most part there aren't a lot of _special_ knobs when compiling the _compiler_ (as opposed to using the compiler executable to compile something else). So it's not really worth creating a separate document. Also, if we create a _separate_ document, there's a risk it'll never be read. So I prefer the current arrangement, unless we have a lot of added material we can add for this case.

[GCC 14 looks to be introducing new configuration options](https://gcc.gnu.org/gcc-14/changes.html) for the compiler itself which could be relevant to this section:
- `--enable-host-pie` will build the compiler executables as PIE 
- `--enable-host-bind-now` will link the compiler executables with -Wl,-z,now
