### ISSUE TITLE
Consider documenting additional tooling

### ISSUE THREAD

**Issue by AaronBallman** [ossf/wg-best-practices-os-developers#337]
The document doesn’t say much about static analysis but it possibly should. Clang and GCC both have builtin static analysis capabilities that could be documented. Compilers are working on adding support for SARIF so that their diagnostics can be ingested by other static analysis tools for improved reporting and tracking capabilities, which might also be worth mentioning.

Additionally, maybe the document should mention `clang-tidy` as a tool that Clang supports which has other checks that are similar to static analysis checks but done with AST pattern matching as opposed to control or data flow analysis. There is some amount of support for common security-related coding guidelines like CERT secure coding or C++ Core Guidelines. You could then mention resources like http://www.cert.org/secure-coding/products-services/secure-coding-download.cfm and http://cert.org/secure-coding/products-services/secure-coding-cpp-download-2016.cfm as free resources people could familiarize themselves with.

**Comment by thomasnyman** [comment]
@AaronBallman: Happy the Compiler Hardening Guide brought you to also other great work done in the context of OpenSSF. Closing this one for now.
