### ISSUE TITLE
Proposed High-Level Vuln Workflow

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/wg-best-practices-os-developers#38]
To assist us in understanding the user stories we want to address as part of this working group I started drawing out a high-level workflow of the process of finding and fixing vulnerabilities in open source and third-party components that I'd love to get everyone's feedback on.

As the diagram is viewed, let me explain the elements/convergences.
There are at least 3 separate working groups working to address part of the problem "How do vulnerabilities get fixed within OSS software" (probably also several others I'm unaware of): 
**OpenSSF Vulnerability Disclosure Group** - OSS maintainer/ecosystem-focused, trying to standardize and provide guidance on vulnerability remediation in OSS components. This is the "head-end" of the process from my perspective.
**OpenSSF Developer Best Practice Group** - OSS maintainer-focused, trying to provide guidance and resources around secure software development, which elements include reacting to vulnerabilities as they are identified (and
 techniques/tools to capture them before they become escapes).  This is the longer-term. lessons-learned, teaching aspect that will help share whatever standards processes the community agrees upon.
**FIRST PSIRT Third Party Component Management Group** - Focused on Vendors/Suppliers that consume (or are involved on some level) with third party hardware and software components.

The diagram shows a high-level flow from when a vuln gets report to where an fix is released to where a downstream supplier picks that fix up and provides it to their consumers.  Our OpenSSF groups are only primarily concerned with the first few steps of this where a Reporter/Finder and Maintainer/Project interact and fix the issue (or not).  There are several external factors like industry standards, concepts like secure supply chain, slide, or software bill of materials that are related to this process, but not directly part of the work we're concerned with at this stage (or in these particular groups).  The Supplier piece is also less interesting to maintainers, so I'm not looking for feedback on that angle in this forum at this point (if you have feels about it, let me know and I can get that to the appropriate group).

I welcome thoughts, suggestions, collaboration on the attached diagram and the concepts detailed within.  Hopefully this can help us focus in on the gaps/pain points of this process to address developer/maintainer concerns.  Thanks!

[OpenSSF Vuln & Dev Diagrams - Workflow.pdf](https://github.com/ossf/wg-best-practices-os-developers/files/5851534/OpenSSF.Vuln.Dev.Diagrams.-.Workflow.pdf)

**Comment by torgo** [comment]
Can we close this issue based on #80 ?

**Comment by torgo** [comment]
Agreed to close on call.
