### ISSUE TITLE
Security Knowledge Framework Demo site certificate has expired

### ISSUE THREAD

**Issue by raesene** [ossf/wg-best-practices-os-developers#40]
I was looking at the demo site (https://demo.securityknowledgeframework.org/) today  and I noticed that the cert. expired on the 6th.

```
 openssl s_client -showcerts -connect demo.securityknowledgeframework.org:443
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = *.securityknowledgeframework.org
verify error:num=10:certificate has expired
notAfter=Sep  6 10:18:48 2021 GMT
verify return:1
depth=0 CN = *.securityknowledgeframework.org
notAfter=Sep  6 10:18:48 2021 GMT
verify return:1
```

**Comment by david-a-wheeler** [comment]
I've alerted Glenn Ten Cate @blabla1337

**Comment by blabla1337** [comment]
Aah let me fix that :)

**Comment by 4390c336** [comment]
configuring certbot to automate the cert renewal is probably the best option to resolve this once for all

**Comment by blabla1337** [comment]
Yes I agree, had it running but for some reason it failed. Need to investigate but for now I did it manually and it's correct again.
Many thanks for reporting it :)

Kind regards,
Glenn
