### ISSUE TITLE
C fallthrough: Which version of the Linux kernel?

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/wg-best-practices-os-developers#480]
The current text says, "The C17 standard does not provide a mechanism to mark intentional fallthroughs....". It then notes the Linux kernel. Is it version 5.10 or 6.4 that started using this?

**Comment by 06kellyjac** [comment]
Commits I've found for `fallthrough`

* https://github.com/torvalds/linux/commit/f7a858bffcddaaf70c71b6b656e7cc21b6107cec [v6.4-rc1](https://github.com/torvalds/linux/releases/tag/v6.4-rc1)
* https://github.com/torvalds/linux/commit/192614010a5052fe92611c7076ef664fd9bb60e8 ([v4.11-rc1](https://github.com/torvalds/linux/releases/tag/v4.11-rc1))
* https://github.com/torvalds/linux/commit/b5bf1733d6a391c4e90ea8f8468d83023be74a2a ([v4.11-rc1](https://github.com/torvalds/linux/releases/tag/v4.11-rc1))

Could be missing some bits. I've not found a reference around 5.10

**Comment by thomasnyman** [comment]
I am also not sure where the reference to 5.10 originates from. I was responsible for adding the last sentence of the section, referring to 6.4 after I also found https://github.com/torvalds/linux/commit/192614010a5052fe92611c7076ef664fd9bb60e8 to be the first commit with `fallthrough` in the form the guide originally referred to. 

Addressing this inconsistency in #494 that also removes the redundant note below the example.
