### ISSUE TITLE
Add security of machine learning systems to guidelines

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/wg-best-practices-os-developers#51]
Add machine learning to:
https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/Existing%20Guidelines%20for%20Developing%20and%20Distributing%20Secure%20Software.md

Here's a source of some information:
https://dwheeler.com/secure-class/presentations/Secure-Software-10-Misc.ppt

More information welcome!

**Comment by david-a-wheeler** [comment]
One way to consider ML issues is to divide them into three categories (as noted in my slide deck, see its citations):

1. Do [Infer] the wrong thing (“Evasion”), Technical term: Adversarial inputs / adversarial examples - Camouflage/optical illusion to fool ML algorithm. E.g., [Szegedy et al 2013].
2. Learn the wrong thing (“Poisoning”). Technical term: data poisoning/Trojan attack. Affect AI ontology to make it wrong
E.g., [Gu et al 2017]
3. Reveal the wrong thing (“Lose Confidentiality”). Technical term: Model inversion. Recover training data points, absence, training data statistics. See [Fredrikson et al 2014]

My primary concern has been the first one, evasion / countering adversarial inputs. There are many techniques to counter evasion, but every measure I've found so far is ineffective. It's easy to find a paper that says "do X to counter adversarial inputs", but most of the authors seem to publish without trying to attack their proposal. There always seems to be another paper showing that the first paper is easily defeated. See my slides for more. *Please* prove me wrong, I spent hours trying to find a technique that is reasonably successful against a not-stupid adversary. But it's been a while since I looked into it, & all it takes is one good idea (with the research to back it up) to eliminate that concern.

I *think* Aeva Black was discussing the *second* issue, learning the wrong thing / poisoning. I haven't focused as much on that, but I can *definitely* believe that this is something where there's useful guidance we can provide today. Aeva can correct me if I misunderstood. Even better, maybe some suggestions / citations :-) ?

**Comment by david-a-wheeler** [comment]
NIST has a draft document NISTIR 8269, "A Taxonomy and Terminology of Adversarial Machine Learning". The draft was released Oct 2019, but there doesn't seem to be a final one even years later: https://csrc.nist.gov/publications/detail/nistir/8269/draft

However, note that this NIST document simply tries to define terms & a taxonomy of approaches - it does NOT claim that anything it identifies actually works. In particular, in the area what it calls "testing (inference)" (actually *using* ML), it appears to be a careful taxonomy & analysis of the approaches that don't work. That may be why they never finished writing the document.

Again, *please* prove me wrong. We just need a single approach that works to prove me wrong, and I can't think of a fundamental reason that evasion can't be effectively countered. My information could easily be made out-of-date, it's been a little while since I delved into this.

**Comment by david-a-wheeler** [comment]
@AevaOnline @SecurityCRob - your turn :-).

**Comment by AevaOnline** [comment]
My meta-question was, "should AI/ML security be considered in scope?" Yesterday's consensus seemed to be "Yes", even if availability of tools supporting it is "debatable".

This is a (commercial) example of the kind of thing I had in mind when asking this question: https://developer.ibm.com/patterns/integrate-adversarial-attacks-model-training-pipeline/

As @david-a-wheeler points out, and which I can neither refute nor claim to be an expert on, it is possible that there are not any _good_ solutions in this space yet.

**Comment by david-a-wheeler** [comment]
@AevaOnline - I agree with the consensus yesterday that AI/ML should be in-scope.

If there aren't any good guidelines that help in an area, it's still useful to note, "this is an area where there are no known good defenses - don't use AI/ML in areas with this kind of security threat unless you find something we don't know about".

**Comment by torgo** [comment]
We discussed briefly today in call - there may be some scope for security of ML systems...   Could go into the backlog of the education SIG or cross-WG topic.

**Comment by david-a-wheeler** [comment]
Perhaps send to education SIG (perhaps add to future training).

Could also ask the related LF foundation https://lfaidata.foundation/ to see if there's an evasion solution.

**Comment by david-a-wheeler** [comment]
LF AI & Data suggested noting ART: https://github.com/Trusted-AI/adversarial-robustness-toolbox/wiki/

I propose adding a short section to the OpenSSF course: https://github.com/ossf/secure-sw-dev-fundamentals

Going into *all* the details is probably too much, but giving people some information about the potential security issues, warning them about some things that don't work, and then pointing them to tools like ART is probably wise. Otherwise many people using AI (including ML) will think security issues don't apply.

**Comment by david-a-wheeler** [comment]
Instead of adding it to the list of guidelines (because there's not much there), let's tweak the OpenSSF fundamentals course instead.

Here's a first cut:

https://github.com/ossf/secure-sw-dev-fundamentals/pull/91

Improvements welcome.

**Comment by david-a-wheeler** [comment]
This has been overtaken by events. There's brief material in the fundamentals course, and there's a separate AI/ML group that's trying to form an OpenSSF working group. So let's just close this here.
