### ISSUE TITLE
Python guide: add SPDX license headers to Python code examples

### ISSUE THREAD

**Issue by gkunz** [ossf/wg-best-practices-os-developers#529]
The Python code examples are licensed under the MIT license, which is in compliance with the OpenSSF charter. To make that clear, we should add the corresponding SPDX license headers.

**Comment by david-a-wheeler** [comment]
I think it'd look like this at the top:

~~~~python
# Copyright OpenSSF project contributors
# SPDX-License-Identifier: MIT
~~~~

**Comment by gkunz** [comment]
Yes, including the copyright is reasonable. We may they use the formal `SPDX-FileCopyrightText` tag: https://spdx.github.io/spdx-spec/v2.2.2/file-tags/

Objections?
