### ISSUE TITLE
Move to archive security toolbelt

### ISSUE THREAD

**Issue by mlieberman85** [ossf/wg-best-practices-os-developers#535]
See: https://github.com/ossf/toolbelt/issues/14

**Comment by hythloda** [comment]
I can not archive things in GitHub anymore. GitHub repo settings are only changeable by admin and owners.  I can't even assign issues in GitHub but the TAC +GC repo, so I will ping @bbpursell1 on this request. Or someone with write can assign to him.

**Comment by gkunz** [comment]
@riaankleinhans can you help with this and https://github.com/ossf/toolbelt/issues/14 in extension?

**Comment by riaankleinhans** [comment]
Achieved
