### ISSUE TITLE
WG Request

### ISSUE THREAD

**Issue by RedHatCRob** [ossf/wg-best-practices-os-developers#6]
Hi there.  My name is CRob and I work for Red Hat Product Security.  In addition to the vulnerability management processes for the company, we are also responsible for governance and SDLC-like activities across our OSS-based portfolio.  I'm interested in joining this group to help further the OSSF initiative and larger community efforts around improving open source software.  I'm heavily involved in the PSIRT community and spend a lot of time educating industry and customers about securing open source software.  I'm looking forward to collaborating with everyone soon!

-CRob

**Comment by xcorail** [comment]
Hi @RedHatCRob 
Can you please send me privately your email address so that I can invite you to our meetings?

**Comment by xcorail** [comment]
Invite send
