### ISSUE TITLE
net::ERR_CERT_AUTHORITY_INVALID for www.bestpractices.dev

### ISSUE THREAD

**Issue by bkimminich** [ossf/wg-best-practices-os-developers#616]
![image](https://github.com/user-attachments/assets/5c26dde9-241c-45ff-bb3d-ce3072d53881)

Just noticed this because my badge was no longer loading on https://juice-shop.github.io/juice-shop/#/12 and https://github.com/juice-shop/juice-shop?tab=readme-ov-file#-owasp-juice-shop etc.

**Comment by degenaro** [comment]
Websites prove their identity via certificates, which are valid for a set time period. The certificate for www.bestpractices.dev expired on 9/8/2024.
 
Error code: [SEC_ERROR_EXPIRED_CERTIFICATE](about:certerror?e=nssBadCert&u=https%3A//www.bestpractices.dev/en&c=UTF-8&d=%20#certificateErrorDebugInformation)

**Comment by david-a-wheeler** [comment]
The TLS certificate expired on 2024-09-09, due to an authentication failure in our automated TLS update process. We fixed it later the same day. Thanks for letting us know!

You can see more here: https://github.com/coreinfrastructure/best-practices-badge/issues/2166
