### ISSUE TITLE
Fix image on home page

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/wg-best-practices-os-developers#62]
The image on the home page needs some fixing:

* Remove "edX' because the course is on multiple platforms
* Rename "CII" to "OpenSSF" on the badge.

@SecurityCRob - do you have the original image to edit?

**Comment by SecurityCRob** [comment]
i DO.  Let me find it and do some edits

**Comment by SecurityCRob** [comment]
uploaded updated graphic today!
