### ISSUE TITLE
Add recommendations for building linkers

### ISSUE THREAD

**Issue by thesamesam** [ossf/wg-best-practices-os-developers#623]
We need a similar section to "What should you do when compiling compilers?" for linkers.

Noticed when looking at https://github.com/ossf/wg-best-practices-os-developers/pull/622.

Some initial candidates for GNU Binutils:
* `--disable-default-execstack`
* `--enable-error-execstack`
* `--enable-relro`
* `--enable-secureplt` (for ppc)
* `--enable-textrel-check=error`
* `--enable-separate-code` / `--enable-rosegment` (although do see https://github.com/ossf/wg-best-practices-os-developers/issues/588#issuecomment-2312549337)

**Comment by david-a-wheeler** [comment]
+1, makes sense to me. Would you be willing to create a first draft pull request?

**Comment by thesamesam** [comment]
Happily, will do.
