### ISSUE TITLE
Seeking new WG Chair

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/wg-best-practices-os-developers#630]
Hello friends!  After 4 years in participating and helping lead the BEST Working Group here at the OpenSSF I am asking our group if there is someone new that is interested in helping lead our merry band?  I'm going through a job transition, and I'd like it very much if someone from our community would take the lead in facilitating the working group so we can continue to be successful in the future.  I'll still be participating as the new role allows, but I want to ensure we have someone(s) in place to continue helping the group be successful and continue to deliver our high-value work to the community.  "Patches Welcome!"

**Comment by balteravishay** [comment]
Those are some large shoes to fill! 
I'm interested in this! if anyone is keen on sharing the role, i'm happy to!

**Comment by gkunz** [comment]
In terms of sharing the role, I'd be happy to help, too.

**Comment by SecurityCRob** [comment]
The group has agreed on the 8Oct2024 call that we'd love to have Avishay and Georg help lead the team!
