### ISSUE TITLE
RC npm Best Practices Guide: package content guidance

### ISSUE THREAD

**Issue by jason-ha** [ossf/wg-best-practices-os-developers#66]
Propose to add section providing guidance on the content of a published package to improve security for consumers.

Basic guidance recommended: package the smallest set of content that allows delivery of intended functionality.

Rationale:
1. All of the content bundled in a package is accessible and provides opportunity for abuse without directly contributing to the intended functionality of the package.
2. It is also difficult and impractical to ascertain what content of a package is required from the point of view of any consumer. The further removed a consumer is from [indirect] dependencies the harder it becomes to understand what is actually relevant/required.
3. Tools that may scan for issues will be most thorough by scanning all of the content. Keeping the content small will reduce cost, improve turn-around time, and may allow for more thorough analysis.

Examples of content that should be excluded include helper files used to generate the package and files used for verification including test data and code.

**Comment by torgo** [comment]
This looks like it can be closed as the guide has been publshed.

**Comment by SecurityCRob** [comment]
https://github.com/ossf/package-manager-best-practices/blob/main/published/npm.md

**Comment by jason-ha** [comment]
@torgo, @SecurityCRob, why does publishing mean it can be closed? Or maybe the funniness is closing as completed rather as rejected? There is no text in the guide to the effect recommended.
