### ISSUE TITLE
Sanitizers need a bigger caveat with suid binaries at least

### ISSUE THREAD

**Issue by thesamesam** [ossf/wg-best-practices-os-developers#661]
We should make clearer that sanitizers should not be used in production, at least not without minimal runtime (see https://github.com/ossf/wg-best-practices-os-developers/issues/326). Needs to be checked whether GCC's just-trap option for sanitizers is similar enough.

Using sanitizers in production with suid binaries can introduce privilege escalation vulnerabilities if a runtime is used as `ASAN_OPTIONS` or `UBSAN_OPTIONS` (possibly others) allow specifying an arbitrary log file path. See https://www.openwall.com/lists/oss-security/2016/02/17/9.

**Comment by thomasnyman** [comment]
Made a proposal for adding this caveat to the beginning of Section 5 in #670.
