### ISSUE TITLE
Meeting times?

### ISSUE THREAD

**Issue by fkautz** [ossf/wg-best-practices-os-developers#8]
When are the meeting times? I can see regular meetings tend to occur at the start of every month but I cannot find any details on when they are. Would be good to add this to the README of this repo.

Thanks!

**Comment by xcorail** [comment]
Hey, the meetings are held every 2 weeks, on Mondays 8am PST.
Next one is Monday Aug 31st

**Comment by xcorail** [comment]
Added in the README
