### ISSUE TITLE
Vendor neutrality when it comes to tools

### ISSUE THREAD

**Issue by torgo** [ossf/wg-best-practices-os-developers#81]
The current version of the [concise guide](https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/Concise-Guide-for-Developing-More-Secure-Software.md) lists:

> “Monitor known vulnerabilities in your software’s direct & indirect dependencies. E.g., use GitHub [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) & GitLab [dependency scanning](https://docs.gitlab.com/ee/user/application_security/dependency_scanning/). Quickly update vulnerable dependencies.”

I'd like to suggest that this needs to be more vendor neutral, either by removing references to specific dependency tracking tools entirely or by listing more tools…?

**Comment by blabla1337** [comment]
I don't really agree with his, we need some applicable examples of tools that are free and easy to use for developers.

As Github and Gitlab are the most common used code repository platforms used for hosting open source software I think referring to these 2 examples is perfectly ok in this situation.
