### ISSUE TITLE
Memory Safety Languages

### ISSUE THREAD

**Issue by mcarthur-cpt** [ossf/wg-best-practices-os-developers#9]
I believe that one of the practices should be to do most if not all the code in modern, memory safe languages like Rust.

**Comment by david-a-wheeler** [comment]
My understanding is that this group is intended to be not advocate any specific programming languages. So our goal is *not* to advocate Rust. (I *like* Rust, but this isn't the place for specific language advocacy.) We can certainly advocate using languages that are memory-safe by default, where that's reasonable to do. Almost all languages are memory-safe by default, including Python, Java, Ruby, Rust, Ada, COBOL, etc.

The [OpenSSF fundamentals course](https://github.com/ossf/secure-sw-dev-fundamentals/blob/main/secure_software_development_fundamentals.md) already strongly recommends memory-safe languages:

> The simplest solution: always, where practical, use memory-safe languages and keep memory safety on. Almost all programming languages are memory-safe, at least by default. If you try to access a buffer outside of its bounds in a memory-safe language, it will resize the buffer or give you an error (typically an exception). In either case, the system doesn’t just cede control to an attacker. This solution is easier to apply when you are writing code from scratch, of course.

One change we *could* make would be to recommend using memory-safe languages, with the safeties maximally enabled, where practical, in the concise guide: https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/Concise-Guide-for-Developing-More-Secure-Software.md#readme

**Comment by david-a-wheeler** [comment]
I think we're done, it's in the recommendations in the concise guide and the fundamentals course.

**Comment by SecurityCRob** [comment]
This has been addressed in the existing training materials
