### ISSUE TITLE
Add "suggestions welcome" to concise guides and contributing.md 

### ISSUE THREAD

**Issue by torgo** [ossf/wg-best-practices-os-developers#93]

**Comment by torgo** [comment]
We discussed recommending that people open issues before opening up PRs...

**Comment by mrybczyn** [comment]
The pull request for concise guides: https://github.com/ossf/wg-best-practices-os-developers/pull/108

**Comment by mrybczyn** [comment]
The README pull request: https://github.com/ossf/wg-best-practices-os-developers/pull/109

**Comment by SecurityCRob** [comment]
Changes integrated.  Thanks all.
